services:
  automation-api:
    image: liamgwallace/scheduler_tool:latest  # Use the Docker Hub image
    ports:
      - "8000:8000"
      - "5000:5000"
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./repos:/repos
    restart: always
    networks:
      - web

networks:
  web:
    external: true
