#1
services:
  automation-api:
    build:
      context: .  # Build context is current directory
    ports:
      - "8000:8000"
      - "5000:5000"
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./repos:/repos
    restart: always
    networks:
      - web

networks:
  web:
    external: true
